"""initial_schema

Revision ID: 63ca0d9086cb
Revises:
Create Date: 2026-04-06 11:21:43.000213

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '63ca0d9086cb'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('int_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('period', sa.Enum('ONE_MIN', 'FIVE_MIN', 'FIFTEEN_MIN', 'SIXTY_MIN', 'DAILY', 'WEEKLY', 'MONTHLY', name='periodenum'), nullable=False),
    sa.Column('level_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('level_type', sa.Enum('SUPPORT', 'RESISTANCE', 'TRENDLINE', 'CHANNEL', 'SWING_HIGH', 'SWING_LOW', name='leveltypeenum'), nullable=False),
    sa.Column('touches_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_int_levels_stock_code'), 'int_levels', ['stock_code'], unique=False)
    op.create_table('klines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_klines_period'), 'klines', ['period'], unique=False)
    op.create_index(op.f('ix_klines_stock_code'), 'klines', ['stock_code'], unique=False)
    op.create_index('ix_klines_stock_period_time', 'klines', ['stock_code', 'period', 'time'], unique=False)
    op.create_index(op.f('ix_klines_time'), 'klines', ['time'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_code'), 'stocks', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('funds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frozen', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('initial_capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_user_id'), 'funds', ['user_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=True),
    sa.Column('order_type', sa.Enum('BUY', 'SELL', name='ordertypeenum'), nullable=False),
    sa.Column('order_mode', sa.Enum('MARKET', 'LIMIT', name='ordermodeenum'), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('filled_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'FILLED', 'CANCELLED', name='orderstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_stock_code'), 'orders', ['stock_code'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('pattern_marks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('period', sa.Enum('ONE_MIN', 'FIVE_MIN', 'FIFTEEN_MIN', 'SIXTY_MIN', 'DAILY', 'WEEKLY', 'MONTHLY', name='periodenum'), nullable=False),
    sa.Column('pattern_type', sa.Enum('PIN_BAR', 'ENGULFING', 'EVENING_STAR', 'MORNING_STAR', 'DOJI', 'HEAD_SHOULDERS_TOP', 'HEAD_SHOULDERS_BOTTOM', name='patternenum'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('start_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('end_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_marks_stock_code'), 'pattern_marks', ['stock_code'], unique=False)
    op.create_index(op.f('ix_pattern_marks_user_id'), 'pattern_marks', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_stock_code'), 'positions', ['stock_code'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_table('sr_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('period', sa.Enum('ONE_MIN', 'FIVE_MIN', 'FIFTEEN_MIN', 'SIXTY_MIN', 'DAILY', 'WEEKLY', 'MONTHLY', name='periodenum'), nullable=False),
    sa.Column('level_type', sa.Enum('SUPPORT', 'RESISTANCE', 'TRENDLINE', 'CHANNEL', 'SWING_HIGH', 'SWING_LOW', name='leveltypeenum'), nullable=False),
    sa.Column('level_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('is_ai_detected', sa.Boolean(), nullable=True),
    sa.Column('is_user_corrected', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sr_levels_stock_code'), 'sr_levels', ['stock_code'], unique=False)
    op.create_index(op.f('ix_sr_levels_user_id'), 'sr_levels', ['user_id'], unique=False)
    op.create_table('trade_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=True),
    sa.Column('period', sa.Enum('ONE_MIN', 'FIVE_MIN', 'FIFTEEN_MIN', 'SIXTY_MIN', 'DAILY', 'WEEKLY', 'MONTHLY', name='periodenum'), nullable=False),
    sa.Column('pattern_type', sa.Enum('PIN_BAR', 'ENGULFING', 'EVENING_STAR', 'MORNING_STAR', 'DOJI', 'HEAD_SHOULDERS_TOP', 'HEAD_SHOULDERS_BOTTOM', name='patternenum'), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('profit_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('trade_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_logs_stock_code'), 'trade_logs', ['stock_code'], unique=False)
    op.create_index(op.f('ix_trade_logs_user_id'), 'trade_logs', ['user_id'], unique=False)
    op.create_table('trade_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='reportperiodenum'), nullable=False),
    sa.Column('period_date', sa.DateTime(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('win_count', sa.Integer(), nullable=True),
    sa.Column('loss_count', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_reports_user_id'), 'trade_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_reports_user_id'), table_name='trade_reports')
    op.drop_table('trade_reports')
    op.drop_index(op.f('ix_trade_logs_user_id'), table_name='trade_logs')
    op.drop_index(op.f('ix_trade_logs_stock_code'), table_name='trade_logs')
    op.drop_table('trade_logs')
    op.drop_index(op.f('ix_sr_levels_user_id'), table_name='sr_levels')
    op.drop_index(op.f('ix_sr_levels_stock_code'), table_name='sr_levels')
    op.drop_table('sr_levels')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_stock_code'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_pattern_marks_user_id'), table_name='pattern_marks')
    op.drop_index(op.f('ix_pattern_marks_stock_code'), table_name='pattern_marks')
    op.drop_table('pattern_marks')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_stock_code'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_funds_user_id'), table_name='funds')
    op.drop_table('funds')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stocks_code'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_klines_time'), table_name='klines')
    op.drop_index('ix_klines_stock_period_time', table_name='klines')
    op.drop_index(op.f('ix_klines_stock_code'), table_name='klines')
    op.drop_index(op.f('ix_klines_period'), table_name='klines')
    op.drop_table('klines')
    op.drop_index(op.f('ix_int_levels_stock_code'), table_name='int_levels')
    op.drop_table('int_levels')
    # ### end Alembic commands ###
